# This is a basic workflow to help you get started with Actions

name: Hello World

on: [push, pull_request]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./
